# Generated by Django 4.2.11 on 2024-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('GBP', 'British Pound Sterling')], max_length=3, unique=True),
        ),
    ]
