# Generated by Django 4.2.11 on 2024-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyexchangerate',
            name='is_protected',
            field=models.BooleanField(default=True),
        ),
    ]
