# Generated by Django 4.2.11 on 2024-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_providermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='priority',
            field=models.IntegerField(default=100, help_text='The default provider has lowest priority value'),
        ),
    ]
